Refactor/vir 149 discussion modify
SWM-Codection/Codection-Review-Service pull request #33
Opened 2024-08-06 14:18 UTC by Lieslot

한 일
---
- DiscussionAllContent 도메인 객체를 삭제
- modifyDiscussion시 DiscussionAllContent를 사용하는 대신 discussion code와 discussion을 나누어서 처리하도록 변경
- modifyDiscussion, updateDiscussion 메소드에 대한 테스트 코드 추가

2024-08-06 14:36 UTC, cloudchamb3r requested changes
전반적으로 LGTM 입니다만, 린트 해결해주시고 .gradle/ 하위에 올라온 파일들도 제외해주시면 좋겠습니다

2024-08-06 15:06 UTC, cloudchamb3r approved these changes
LGTM

2024-08-06 17:52 UTC, sangcheol12 requested changes
수고하셨습니다.
리뷰 읽어보시고 관련 내용 의견 부탁드려요

2024-08-06 17:52 UTC, sangcheol12 commented on src/main/kotlin/swm/virtuoso/reviewservice/adapter/in/web/controller/DiscussionController.kt
>          request: ModifyDiscussionRequest
지난 머지에서 반영되어 여기서 보이지는 않지만  Request인데 얘만 Response 폴더 안에 존재하는데 수정해주세요

2024-08-06 17:52 UTC, sangcheol12 commented on src/main/kotlin/swm/virtuoso/reviewservice/adapter/out/persistence/DiscussionPersistenceAdapter.kt
> +        discussion.index = getNextIndex(discussion.repoId)
업데이트에서 인덱스를 새로 구하는 이유가 있을까요?

2024-08-06 17:52 UTC, sangcheol12 commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
현재 코드 로직에 문제가 있는 것은 아니지만 title 혹은 content 하나만 바꾸더라도 참조하는 코드를 모두 보내주어야 합니다. 그러한 이유로 현재 범위 또한 참조 코드 변경 로직과 디스커션 정보 변경 두가지 역할을 하게 되고요.
따라서 api를 참조하는 코드들을 변경하는 부분과 디스커션의 내용을 변경하는 부분으로 분리하는 것이 좋을 것 같다는 생각이 듭니다.
@cloudchamb3r  @Lieslot

2024-08-07 01:00 UTC, Lieslot commented on src/main/kotlin/swm/virtuoso/reviewservice/adapter/out/persistence/DiscussionPersistenceAdapter.kt
> +        discussion.index = getNextIndex(discussion.repoId)
예전에 논의했을 때 수정된 디스커션을 강조하기 위해 인덱스를 업데이트해서 맨 위로 올리자는 의견이 있어서 들어갔던 거 같은데 정렬 기능이 있어서  굳이 필요한지는 잘 모르겠네용. 일단 빼는 게 나을 거 같긴 합니다.

2024-08-07 01:12 UTC, cloudchamb3r commented on src/main/kotlin/swm/virtuoso/reviewservice/adapter/out/persistence/DiscussionPersistenceAdapter.kt
> +        discussion.index = getNextIndex(discussion.repoId)
인덱스를 업데이트할때마다 바꾸자는 의견은 못들었던거 같은데.. 여기서는 확실히 getNextIndex() 호출하지 않는 게 맞다고 봅니다

2024-08-07 01:12 UTC, Lieslot commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
프론트가 다소 번거로울 수 있다는 생각이 들긴하지만 일단 저는 동의합니당. 그리고 지금 수정 시에 기존에 있던 코드 블록을 수정을 추가 삭제만 가능한 상태인데 equals 메소드를 오버라이드해서 id를 제외한 나머지 필드는 비교 연산에서 배제하는 게 좋아보이긴 하네요.

2024-08-07 01:20 UTC, Lieslot commented on src/main/kotlin/swm/virtuoso/reviewservice/adapter/out/persistence/DiscussionPersistenceAdapter.kt
> +        discussion.index = getNextIndex(discussion.repoId)
https://github.com/SWM-Codection/Codection-Review-Service/commit/fc1eb026ed5c21c3ff2a6de7d1abc639335c6ff9#diff-2a75c346657f93f3d301c5d17453b9a321cba2661798312be2b9dba205981e58

이 커밋 반영하기 전에 둘이서 페어 프로그래밍 했었는데 그 때 그런 말이 나왔던 거 같아요.

2024-08-07 01:22 UTC, cloudchamb3r commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
https://github.com/SWM-Codection/Codection-Review-Service/blob/refactor/VIR-149-Discussion-Modify/src/main/kotlin/swm/virtuoso/reviewservice/adapter/in/web/dto/response/ModifyDiscussionRequest.kt

여기 보니까 codes 에 @NotEmpty 붙어있긴하네요 
사실 굳이 보내야 싶긴합니다

2024-08-07 01:28 UTC, cloudchamb3r commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
@sangcheol12 
엔드포인트를 나누자는 걸까요 아니면 서비스의 역할만 따로 나누자는 걸까요?
엔드포인트를 나누게 되면, 
제목만 수정했을때
내용만 수정했을때
제목과 내용을 모두 수정했을때
 따로 분기해서 처리해야하나요? 

엔드포인트에 관해서는 그냥 한가지 엔드 포인트에서 처리하는게 맞다고 봅니다

2024-08-07 01:54 UTC, sangcheol12 commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
엔드포인트를 나누자는 말은 맞지만 제목만 타이틀만 이렇게 하나하나까지 나눌 필요는 없다 생각합니다. 그러나 참조 코드가 많을 수 있고 엄밀히 디스커션과 디스커션 코멘트는 다른 도메인 객체이므로 두가지만 분류하는 것이 코드 및 네트워크 상으로 적합하다 생각합니다
분리한다면 이 부분은 프론트에도 적용되는 부분이므로 급하게 처리 할 필요는 없고 이슈로 등록 후 추후 처리해도 괜찮을 것 같습니다

2024-08-07 02:00 UTC, cloudchamb3r commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
네트워크 비용이 문제라면, 변경 사항이 아닌 곳엔 null 과 같은 센티널 값들을 전달하고, 변경사항에만 한해 전달하면 된다고 생각합니다. 
제가 이쪽 부분에 대해서, 디스커션 코멘트가 변경되는 부분은 찾질 못하겠는데 혹시 어떤 부분인지 설명해주실수 있을까요?

2024-08-07 02:04 UTC, sangcheol12 commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
바로 위의 제가 첨부한 로직을 보면 인지로 들어온 코드들 중 인자에 없다면 제거하고 id가 null인 객체가 들어오면 새로 추가하는 로직이 있습니다
따라서 title하나만 변경 되더라도 현재 참조하고 있는 모든 코드 리스트를 그대로 보내줘야 하는 상황입니다
@cloudchamb3r

2024-08-07 02:04 UTC, Lieslot commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
```       
        val targetCodes = discussionCodePort.findDiscussionCodesByDiscussionId(modifyDiscussionRequest.discussionId)

        val modifiedCodes = modifyDiscussionRequest.codes

        val deletedCodeIds: List<Long> = targetCodes.filterNot { it in modifiedCodes }
            .mapNotNull { it.id } // 삭제할 코드 ID 필터

        val newCodes: List<DiscussionCode> = modifiedCodes.filter { it.id == null } // 추가할 코드 필터링

        discussionCodePort.deleteDiscussionCodeAllById(deletedCodeIds) 코드 삭제
       discussionCodePort.insertDiscussionCodes(newCodes, modifyDiscussionRequest.discussionId) 코드 추가
        ```
 이 부분입니다.

2024-08-07 02:06 UTC, cloudchamb3r commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
코멘트가 아니고 코드 아닌가요? 아리까리해서..

2024-08-07 02:15 UTC, cloudchamb3r commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
일단 코드라 한다해도 여전히 엔드포인트는 하나로 두는게 적합하다고 봅니다
단 서비스를 나누는거에 대해선 취지를 공감하고있습니다

2024-08-07 02:57 UTC, sangcheol12 commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
코멘트가 아닌 코드입니다. 위에는 오타이네요
혹시 엔드포인트가 하나여야 하는 이유가 한전에 관리 할 수 있음 외에 장점이 무엇이 있을까요?

2024-08-07 03:07 UTC, cloudchamb3r commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
한번에 관리할 수 있는 부분이 가장 큽니다.
하나로 합친게 네트워크 비용이 무리가 되는거라면 앞서 말했듯, 변경되지 않는 값들에 대해서는 값을 보내지 않으면 됩니다. 
구현단계에서 그렇게 하더라도 충분히 구현이 가능합니다 

반대로 엔드포인트를 둘로 나누는 상황이라면, 
클라이언트 단에서 단순히 디스커션 수정이라는 한가지 행동을 했을때 
discussion 수정과 discussion code 수정이라는 두가지 엔드포인트에 각각 요청을 보내야합니다. 
저는 이러한 행동은 클라이언트의 행동과 인지측면에서 상당한 문제가 있다고 보고
이에 대해서는 `/discussion/modify` 라는 추상화된 레벨에서 처리해도 괜찮다고 생각합니다

뭐 별도로 성능에 딴지를 걸자면 ㅋㅋ, 두번의 요청은 쓸데없는 HTTP 헤더까지 더 보내게 되니, 코스트는 오히려 작은 코드 변경이라면 더 커질수도 있겠지요

2024-08-07 03:36 UTC, sangcheol12 commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
@cloudchamb3r
넵 변경되지 않은 데이터에 대해서 보내지 않도록 처리 된다면 저도 동의합니다
다만 현재 로직에서는 request로 들어 온 데이터를 바탕으로 없는 것은 모조리 삭제되고 없었던 것은 추가하는 방식이라 모든 데이터의 값이 전달되는 것을 유도하는 것 같습니다
request에서 deletedCodes는 ID만 보낼 수 있도록하고 새로 추가 된 addcodes 것은 모두 보내도록 수정하는 것이 필요합니다
@Lieslot

2024-08-07 03:37 UTC, sangcheol12 commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
추가로 위의 제가 제안한 방안으로 구현한다면 제거하지 않지만 라인 수가 변경되는 등의 modifiedCodes도 확장 할 수 있도록 구현하시면 좋을 것 같습니다

2024-08-07 04:03 UTC, Lieslot commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
논의해본 결과 백엔드 단에서 가장 큰 문제는 엔드포인트 분리 시 트랜잭션을 묶는 게 까다로운 점 같습니다. 엔드 포인트를 분리해버리면 두 엔드 포인트를 모두 사용하는 순간이 왔을 때 하나는 성공하고 하나는 실패했을 때 트랜잭션을 롤백하는 게 정말 까다로워집니다.

2024-08-07 04:03 UTC, cloudchamb3r commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
현재 로직의 일부 수정은 필요할거같습니다. 현재 구현에서 무조건 코드를 보내야한다면, 그건 여전히 문제긴 하겠네요

2024-08-07 04:08 UTC, Lieslot commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
> @cloudchamb3r 넵 변경되지 않은 데이터에 대해서 보내지 않도록 처리 된다면 저도 동의합니다 다만 현재 로직에서는 request로 들어 온 데이터를 바탕으로 없는 것은 모조리 삭제되고 없었던 것은 추가하는 방식이라 모든 데이터의 값이 전달되는 것을 유도하는 것 같습니다 request에서 deletedCodes는 ID만 보낼 수 있도록하고 새로 추가 된 addcodes 것은 모두 보내도록 수정하는 것이 필요합니다 

이에 대해선 저도 그러는 편이 좋다고 생각합니다.
그러면 프론트 쪽에서 삭제 추가와 관련된 로직을 처리해주셔야 할 것 같은데, 괜찮으실까요?  @cloudchamb3r

2024-08-07 04:11 UTC, cloudchamb3r commented on src/main/kotlin/swm/virtuoso/reviewservice/application/service/DiscussionService.kt
> +        return discussionPort.updateDiscussion(discussion = targetDiscussion)
넵 괜찮습니다

2024-08-07 04:34 UTC, Lieslot commented on src/main/kotlin/swm/virtuoso/reviewservice/adapter/out/persistence/DiscussionPersistenceAdapter.kt
> +        discussion.index = getNextIndex(discussion.repoId)
이 부분은 제거했습니다.

2024-08-07 04:39 UTC, sangcheol12 requested changes
이것만 수정하면 될 듯 합니다

2024-08-07 04:39 UTC, sangcheol12 commented on src/main/kotlin/swm/virtuoso/reviewservice/adapter/out/persistence/DiscussionPersistenceAdapter.kt
> +        discussionIndexRepository.save(
해당 부분도 이전과 같은 이유로 제거되어야하는 부분입니다.

2024-08-07 04:42 UTC, Lieslot commented on src/main/kotlin/swm/virtuoso/reviewservice/adapter/out/persistence/DiscussionPersistenceAdapter.kt
> +        discussionIndexRepository.save(
넵 수정 완료했습니당

2024-08-07 04:46 UTC, sangcheol12 approved these changes
LGTM

2024-08-07 04:47 UTC, merged